apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-level-resources
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - helm:
      releaseName: cluster-level-resources
      valueFiles:
      - $values/gen3-luca-play/cluster-level-resources/cluster-values.yaml
    path: helm/cluster-level-resources
    repoURL: 'https://github.com/chicagopcdc/gen3-helm'
    targetRevision: karpeneter-update # can remove later since karpenter is set to false in cluster-values.yaml
  - ref: values
    repoURL: 'https://github.com/chicagopcdc/gen3-gitops'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true